configuration: Release

# restore NuGet packages before running MSBuild
before build:
    - nuget restore

# package Web Application priject for Web Deploy
build:
    verbosity: minimal
    publish_wap: true